### GetRasterCalculatorFile
GET {{raster_calculator_cwl_href}}

>> raster-calculate-app.cwl

### GetLandCoverChangeDetectionFile
GET {{lulc_change_cwl_href}}

>> lulc-change-app.cwl


### ListProcesses
GET {{ades_url}}/{{workspace}}/ogc-api/processes
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### RegiserProcessFromURL
POST {{ades_url}}/{{workspace}}/ogc-api/processes
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json

{ "executionUnit": {"href": "{{raster_calculator_cwl_href}}", "type": "application/cwl" }}

> {%

    client.global.set("register_process_response", response.body);

%}

### RegiserProcessFromBadURL
POST {{ades_url}}/{{workspace}}/ogc-api/processes
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json

{ "executionUnit": {"href": "https://some-site.com/non-existend/cwl/file/spec/path.cwl", "type": "application/cwl" }}

### RegiserProcessFromLocalFile
POST {{ades_url}}/{{workspace}}/ogc-api/processes
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/cwl+yaml

< raster-calculate-app.cwl

> {%

    client.global.set("register_process_response", response.body);

%}

### UnregisterProcess
DELETE {{ades_url}}/{{workspace}}/ogc-api/processes/{{register_process_response.id}}
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### UnregisterNonExistentProcess
DELETE {{ades_url}}/{{workspace}}/ogc-api/processes/i-dont-exist
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### GetProcessDetails
GET {{ades_url}}/{{workspace}}/ogc-api/processes/{{register_process_response.id}}
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### GetNonExistentProcessDetails
GET {{ades_url}}/{{workspace}}/ogc-api/processes/i-dont-exist
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### ExecuteProcess
POST {{ades_url}}/{{workspace}}/ogc-api/processes/{{register_process_response.id}}/execution
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json
Prefer: respond-async

{
    "inputs": {
        "workspace": "{{workspace}}",
        "stac_collection": "sentinel-2-l2a",
        "aoi": "{\"type\":\"Polygon\",\"coordinates\":[[[14.763294437090849,50.833598186651244],[15.052268923898112,50.833598186651244],[15.052268923898112,50.989077215056824],[14.763294437090849,50.989077215056824],[14.763294437090849,50.833598186651244]]]}",
        "date_start": "2024-04-03",
        "date_end": "2024-08-01",
        "index": "ndvi"
    }
}

> {%

    client.global.set("execute_process_response", response.body);

%}

### ExecuteNonExistentProcess
POST {{ades_url}}/{{workspace}}/ogc-api/processes/i-dont-exist/execution
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json
Prefer: respond-async

{
    "inputs": {
        "workspace": "{{workspace}}",
        "stac_collection": "sentinel-2-l2a",
        "aoi": "{\"type\":\"Polygon\",\"coordinates\":[[[14.763294437090849,50.833598186651244],[15.052268923898112,50.833598186651244],[15.052268923898112,50.989077215056824],[14.763294437090849,50.989077215056824],[14.763294437090849,50.833598186651244]]]}",
        "date_start": "2024-04-03",
        "date_end": "2024-08-01",
        "index": "ndvi"
    }
}

### ListJobs
GET {{ades_url}}/{{workspace}}/ogc-api/jobs
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### GetJobStatus
GET {{ades_url}}/{{workspace}}/ogc-api/jobs/{{execute_process_response.jobID}}
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

> {%

    client.global.set("job_status", response.body);

%}

### GetNonExistentJobStatus
GET {{ades_url}}/{{workspace}}/ogc-api/jobs/non-existent-job-id
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### GetNonExistentJobStatus
GET {{ades_url}}/{{workspace}}/ogc-api/jobs/8539da22-7f2e-11ef-92a3-921292eb1c22
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### GetNonExistentJobStatus
GET {{ades_url}}/{{workspace}}/ogc-api/jobs/cadbba82-7f1f-11ef-a100-921292eb1c22/results
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### GetJobResults
GET {{ades_url}}/{{workspace}}/ogc-api/jobs/{{execute_process_response.jobID}}/results
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### GetNonExistentJobResults
GET {{ades_url}}/{{workspace}}/ogc-api/jobs/non-existent-job-id/results
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### GetJobLogs
GET {{job_status.links[2].href}}
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### GetJobStageOutLogs
GET {{job_status.links[3].href}}
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### CancelJob
DELETE {{ades_url}}/{{workspace}}/ogc-api/jobs/{{execute_process_response.jobID}}
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### CancelNonExistentJob
DELETE {{ades_url}}/{{workspace}}/ogc-api/jobs/non-existent-job-id
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### Unregister LULC Change Process
DELETE {{ades_url}}/{{workspace}}/ogc-api/processes/lulc-change
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### Register LULC Change Process
POST {{ades_url}}/{{workspace}}/ogc-api/processes
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/cwl+yaml

< lulc-change-app.cwl

### Get LULC Change Process details
GET {{ades_url}}/{{workspace}}/ogc-api/processes/lulc-change
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### Execute LULC Change Process
POST {{ades_url}}/{{workspace}}/ogc-api/processes/lulc-change/execution
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json
Prefer: respond-async

{
    "inputs": {
        "aoi": "{\"type\":\"Polygon\",\"coordinates\":[[[14.763294437090849,50.833598186651244],[15.052268923898112,50.833598186651244],[15.052268923898112,50.989077215056824],[14.763294437090849,50.989077215056824],[14.763294437090849,50.833598186651244]]]}",
        "date_start": "2006-01-01",
        "date_end": "2024-04-03",
        "source": "esacci-globallc",
        "workspace": "{{workspace}}"
    }
}

> {%

    client.global.set("execute_process_response", response.body);

%}

### Get LULC Change status
GET https://test.eodatahub.org.uk/ades/{{workspace}}/ogc-api/jobs/{{execute_process_response.jobID}}
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json

### Get LULC Change results
GET https://test.eodatahub.org.uk/ades/{{workspace}}/ogc-api/jobs/{{execute_process_response.jobID}}/results
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json
