@raster_calculator_cwl_href=https://raw.githubusercontent.com/EO-DataHub/eodh-workflows/main/cwl_files/raster-calculate-app.cwl
@lulc_change_cwl_href=https://raw.githubusercontent.com/EO-DataHub/eodh-workflows/main/cwl_files/lulc-change-app.cwl
@water_quality_cwl_href=https://raw.githubusercontent.com/EO-DataHub/eodh-workflows/main/cwl_files/water-quality-app.cwl
@ades_url=https://test.eodatahub.org.uk/ades


### List Processes
GET {{ades_url}}/{{username}}/ogc-api/processes
Accept: application/json
Authorization: Bearer {{token}}

### Register Process From URL
POST {{ades_url}}/{{username}}/ogc-api/processes
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{ "executionUnit": {"href": "{{raster_calculator_cwl_href}}", "type": "application/cwl" }}

> {%

    client.global.set("register_process_response", response.body);

%}

### Register Process From Bad URL
POST {{ades_url}}/{{username}}/ogc-api/processes
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{ "executionUnit": {"href": "https://some-site.com/non-existend/cwl/file/spec/path.cwl", "type": "application/cwl" }}

### Register Process FromLocal File
POST {{ades_url}}/{{username}}/ogc-api/processes
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/cwl+yaml

< raster-calculate-app.cwl

> {%

    client.global.set("register_process_response", response.body);

%}

### Unregister Process
DELETE {{ades_url}}/{{username}}/ogc-api/processes/{{register_process_response.id}}
Accept: application/json
Authorization: Bearer {{token}}

### Unregister Non Existent Process
DELETE {{ades_url}}/{{username}}/ogc-api/processes/i-dont-exist
Accept: application/json
Authorization: Bearer {{token}}

### Get Process Details
GET {{ades_url}}/{{username}}/ogc-api/processes/{{register_process_response.id}}
Accept: application/json
Authorization: Bearer {{token}}

### Get Non Existent Process Details
GET {{ades_url}}/{{username}}/ogc-api/processes/i-dont-exist
Accept: application/json
Authorization: Bearer {{token}}

### Execute Process
POST {{ades_url}}/{{username}}/ogc-api/processes/{{register_process_response.id}}/execution
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json
Prefer: respond-async

{
    "inputs": {
        "workspace": "{{username}}",
        "stac_collection": "sentinel-2-l2a",
        "aoi": "{\"type\":\"Polygon\",\"coordinates\":[[[71.57683969558222,4.278154706539496],[71.96061157730237,4.278154706539496],[71.96061157730237,4.62344048537264],[71.57683969558222,4.62344048537264],[71.57683969558222,4.278154706539496]]]}",
        "date_start": "2024-01-01",
        "date_end": "2024-08-01",
        "index": "ndvi",
        "limit": "1",
        "clip": "True"
    }
}

> {%

    client.global.set("execute_process_response", response.body);

%}

### Execute Non Existent Process
POST {{ades_url}}/{{username}}/ogc-api/processes/i-dont-exist/execution
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json
Prefer: respond-async

{
    "inputs": {
        "workspace": "{{username}}",
        "stac_collection": "sentinel-2-l2a",
        "aoi": "{\"type\":\"Polygon\",\"coordinates\":[[[14.763294437090849,50.833598186651244],[15.052268923898112,50.833598186651244],[15.052268923898112,50.989077215056824],[14.763294437090849,50.989077215056824],[14.763294437090849,50.833598186651244]]]}",
        "date_start": "2024-04-03",
        "date_end": "2024-08-01",
        "index": "ndvi"
    }
}

### List Jobs
GET {{ades_url}}/{{username}}/ogc-api/jobs?limit=100&skip=0
Accept: application/json
Authorization: Bearer {{token}}

### Get Job Status
GET {{ades_url}}/{{username}}/ogc-api/jobs/244fb332-de68-11ef-94fd-12e2ea552ab2
Accept: application/json
Authorization: Bearer {{token}}

> {%

    client.global.set("job_status", response.body);

%}

### Get Job Results
GET {{ades_url}}/{{username}}/ogc-api/jobs/{{job_status.jobID}}/results
Accept: application/json
Authorization: Bearer {{token}}

### Get Job Logs
GET {{job_status.links[-1].href}}
Accept: application/json
Authorization: Bearer {{token}}

### Get Job StageOut Logs
GET {{job_status.links[-1].href}}
Accept: application/json
Authorization: Bearer {{token}}

# Failed job handling

### Get Failed Job Logs
GET {{job_status.links[1].href}}
Accept: application/json
Authorization: Bearer {{token}}

### Get Failed Job Stage Out Logs
GET {{job_status.links[-1].href}}
Accept: application/json
Authorization: Bearer {{token}}

### Cancel Job
DELETE {{ades_url}}/{{username}}/ogc-api/jobs/5935d008-bb9b-11ef-b0ed-6a040e2afd6f
Accept: application/json
Authorization: Bearer {{token}}

### Cancel Non Existent Job
DELETE {{ades_url}}/{{username}}/ogc-api/jobs/non-existent-job-id
Accept: application/json
Authorization: Bearer {{token}}

### Get Non Existent Job Status
GET {{ades_url}}/{{username}}/ogc-api/jobs/non-existent-job-id
Accept: application/json
Authorization: Bearer {{token}}

### Get Non Existent Job Status
GET {{ades_url}}/{{username}}/ogc-api/jobs/8539da22-7f2e-11ef-92a3-921292eb1c22
Accept: application/json
Authorization: Bearer {{token}}

### Get Non Existent Job Results
GET {{ades_url}}/{{username}}/ogc-api/jobs/cadbba82-7f1f-11ef-a100-921292eb1c22/results
Accept: application/json
Authorization: Bearer {{token}}

### Get Non Existent Job Results
GET {{ades_url}}/{{username}}/ogc-api/jobs/non-existent-job-id/results
Accept: application/json
Authorization: Bearer {{token}}
