### Get Raster Calculator File
GET {{raster_calculator_cwl_href}}

>> raster-calculate-app.cwl

### Unregister Process
DELETE {{ades_url}}/{{workspace}}/ogc-api/processes/raster-calculate
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### Register Process
POST {{ades_url}}/{{workspace}}/ogc-api/processes
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/cwl+yaml

< raster-calculate-app.cwl

### Get Process details
GET {{ades_url}}/{{workspace}}/ogc-api/processes/raster-calculate
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### Execute Process
POST {{ades_url}}/{{workspace}}/ogc-api/processes/raster-calculate/execution
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json
Prefer: respond-async

{
    "inputs": {
        "workspace": "{{workspace}}",
        "stac_collection": "sentinel-2-l2a",
        "aoi": "{\"type\":\"Polygon\",\"coordinates\":[[[71.57683969558222,4.278154706539496],[71.96061157730237,4.278154706539496],[71.96061157730237,4.62344048537264],[71.57683969558222,4.62344048537264],[71.57683969558222,4.278154706539496]]]}",
        "date_start": "2024-01-01",
        "date_end": "2024-08-01",
        "index": "ndvi",
        "limit": 1,
        "clip": "True"
    }
}

> {%

    client.global.set("execute_process_response", response.body);

%}

### Get Job status
GET https://test.eodatahub.org.uk/ades/{{workspace}}/ogc-api/jobs/{{execute_process_response.jobID}}
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json

> {%

    client.global.set("job_status", response.body);

%}

### Get Job results
GET https://test.eodatahub.org.uk/ades/{{workspace}}/ogc-api/jobs/{{execute_process_response.jobID}}/results
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json

### Get Job Logs
GET {{job_status.links[2].href}}
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### Get Job Stage Out Logs
GET {{job_status.links[3].href}}
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### Get Failed Job Logs
GET {{job_status.links[1].href}}
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### Get Failed Job Stage Out Logs
GET {{job_status.links[2].href}}
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### Cancel Job
DELETE {{ades_url}}/{{workspace}}/ogc-api/jobs/{{execute_process_response.jobID}}
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
