@app_cwl_href=https://raw.githubusercontent.com/EO-DataHub/eodh-workflows/main/cwl_files/water-quality-app.cwl
@app_name=water-quality
@ades_url=https://test.eodatahub.org.uk/ades


### Get Water Quality File
GET {{app_cwl_href}}

>> water-quality-app.cwl

### Unregister Process
DELETE {{ades_url}}/{{username}}/ogc-api/processes/{{app_name}}
Accept: application/json
Authorization: Bearer {{token}}

### Register Process
POST {{ades_url}}/{{username}}/ogc-api/processes
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/cwl+yaml

< water-quality-app.cwl

### Get Process details
GET {{ades_url}}/{{username}}/ogc-api/processes/{{app_name}}
Accept: application/json
Authorization: Bearer {{token}}

### Execute Process
POST {{ades_url}}/{{username}}/ogc-api/processes/{{app_name}}/execution
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json
Prefer: respond-async

{
    "inputs": {
        "workspace": "{{username}}",
        "stac_collection": "sentinel-2-l2a",
        "aoi": "{\"type\":\"Polygon\",\"coordinates\":[[[71.57683969558222,4.278154706539496],[71.96061157730237,4.278154706539496],[71.96061157730237,4.62344048537264],[71.57683969558222,4.62344048537264],[71.57683969558222,4.278154706539496]]]}",
        "date_start": "2024-01-01",
        "date_end": "2024-08-01",
        "limit": 10,
        "clip": "True"
    }
}

> {%

    client.global.set("execute_process_response", response.body);

%}

### Get Job status
GET https://test.eodatahub.org.uk/ades/{{username}}/ogc-api/jobs/{{execute_process_response.jobID}}
Authorization: Bearer {{token}}
Content-Type: application/json

> {%

    client.global.set("job_status", response.body);

%}

### Get Job results
GET https://test.eodatahub.org.uk/ades/{{username}}/ogc-api/jobs/{{execute_process_response.jobID}}/results
Authorization: Bearer {{token}}
Content-Type: application/json

### Get Job Logs
GET {{job_status.links[2].href}}
Accept: application/json
Authorization: Bearer {{token}}

### Get Job Stage Out Logs
GET {{job_status.links[3].href}}
Accept: application/json
Authorization: Bearer {{token}}

### Get Failed Job Logs
GET {{job_status.links[1].href}}
Accept: application/json
Authorization: Bearer {{token}}

### Get Failed Job Stage Out Logs
GET {{job_status.links[2].href}}
Accept: application/json
Authorization: Bearer {{token}}

### Cancel Job
DELETE {{ades_url}}/{{username}}/ogc-api/jobs/73cd79a8-b23a-11ef-a1ea-ee3aaed8a789
Accept: application/json
Authorization: Bearer {{token}}
