### Get S3 credentials
POST https://{{env}}.eodatahub.org.uk/api/workspaces/{{username}}/me/s3-tokens
Authorization: Bearer {{token}}
Accept: application/json

>> tmp_s3_credentials.json

### List Access Token
GET https://{{env}}.eodatahub.org.uk/api/workspaces/{{username}}/me/tokens
Authorization: Bearer {{token}}
Accept: application/json

### Get Access Token
POST https://{{env}}.eodatahub.org.uk/api/workspaces/{{username}}/me/tokens
Authorization: Bearer {{token}}
Accept: application/json

{"name": "API Token", "scope": "offline_access", "expires": 30}

> {%

    client.global.set("access_token_response", JSON.parse(response.body));

%}

### Invalidate Access Token
DELETE https://{{env}}.eodatahub.org.uk/api/workspaces/{{username}}/me/tokens/{{access_token_response.id}}
Authorization: Bearer {{token}}
Accept: */*

### Generate workspac scoped session token
POST https://{{env}}.eodatahub.org.uk/api/workspaces/{{username}}/me/sessions
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
