from __future__ import annotations

from typing import Any

CLIP_FUNCTION_SPEC = {
    "identifier": "clip",
    "name": "Clip",
    "description": "Clip (crop) items generated by previous function using provided Area of Interest.",
    "standalone": False,
    "cwl_href": "https://raw.githubusercontent.com/EO-DataHub/eodh-workflows/main/cwl_files/clip-app.cwl",
    "inputs": {
        "stac_collection": {
            "name": "stac_collection",
            "full_name": "STAC collection",
            "type": "stac_collection",
            "required": True,
            "description": "The STAC collection with items from previous function block.",
        },
        "aoi": {
            "name": "aoi",
            "full_name": "Area of Interest",
            "type": "polygon",
            "required": True,
            "description": "The Area of Interest as GeoJSON (polygon) for item cropping.",
        },
    },
    "outputs": {
        "stac_collection": {
            "name": "stac_collection",
            "full_name": "STAC collection",
            "type": "stac_collection",
            "description": "The STAC collection with results.",
        },
    },
}
NDVI_FUNCTION_SPEC = {
    "identifier": "ndvi",
    "name": "NDVI: Normalised Difference Vegetation Index",
    "description": "Calculates Normalised Difference Vegetation Index.",
    "standalone": True,
    "cwl_href": "https://raw.githubusercontent.com/EO-DataHub/eodh-workflows/main/cwl_files/ndvi-app.cwl",
    "inputs": {
        "stac_collection": {
            "name": "stac_collection",
            "full_name": "STAC collection",
            "type": "string",
            "required": False,
            "default": "sentinel-2-l2a",
            "description": "The STAC collection to use.",
            "options": ["sentinel-2-l2a"],
        },
        "date_start": {
            "name": "date_start",
            "full_name": "Start date",
            "type": "datetime",
            "required": False,
            "description": "The start date and time to use for item filtering. Must be RFC3339 compliant.",
        },
        "date_end": {
            "name": "date_end",
            "full_name": "End date",
            "type": "datetime",
            "required": False,
            "description": "The end date and time to use for item filtering. Must be RFC3339 compliant.",
        },
        "aoi": {
            "name": "aoi",
            "full_name": "Area of Interest",
            "type": "polygon",
            "required": True,
            "description": "The Area of Interest as GeoJSON (polygon).",
        },
    },
    "outputs": {
        "stac_collection": {
            "name": "stac_collection",
            "full_name": "STAC collection",
            "type": "stac_collection",
            "description": "The STAC collection with results.",
        },
    },
}
EVI_FUNCTION_SPEC = {
    "identifier": "evi",
    "name": "EVI: Enhanced Vegetation Index",
    "description": "Calculates Enhanced Vegetation Index.",
    "standalone": True,
    "cwl_href": "https://raw.githubusercontent.com/EO-DataHub/eodh-workflows/main/cwl_files/evi-app.cwl",
    "inputs": {
        "stac_collection": {
            "name": "stac_collection",
            "full_name": "STAC collection",
            "type": "string",
            "required": False,
            "default": "sentinel-2-l2a",
            "description": "The STAC collection to use.",
            "options": ["sentinel-2-l2a"],
        },
        "date_start": {
            "name": "date_start",
            "full_name": "Start date",
            "type": "datetime",
            "required": False,
            "description": "The start date and time to use for item filtering. Must be RFC3339 compliant.",
        },
        "date_end": {
            "name": "date_end",
            "full_name": "End date",
            "type": "datetime",
            "required": False,
            "description": "The end date and time to use for item filtering. Must be RFC3339 compliant.",
        },
        "aoi": {
            "name": "aoi",
            "full_name": "Area of Interest",
            "type": "polygon",
            "required": True,
            "description": "The Area of Interest as GeoJSON (polygon).",
        },
    },
    "outputs": {
        "stac_collection": {
            "name": "stac_collection",
            "full_name": "STAC collection",
            "type": "stac_collection",
            "description": "The STAC collection with results.",
        },
    },
}
SAVI_FUNCTION_SPEC = {
    "identifier": "savi",
    "name": "SAVI: Soil-Adjusted Vegetation Index",
    "description": "Calculates Soil-Adjusted Vegetation Index.",
    "standalone": True,
    "cwl_href": "https://raw.githubusercontent.com/EO-DataHub/eodh-workflows/main/cwl_files/savi-app.cwl",
    "inputs": {
        "stac_collection": {
            "name": "stac_collection",
            "full_name": "STAC collection",
            "type": "string",
            "required": False,
            "default": "sentinel-2-l2a",
            "description": "The STAC collection to use.",
            "options": ["sentinel-2-l2a"],
        },
        "date_start": {
            "name": "date_start",
            "full_name": "Start date",
            "type": "datetime",
            "required": False,
            "description": "The start date and time to use for item filtering. Must be RFC3339 compliant.",
        },
        "date_end": {
            "name": "date_end",
            "full_name": "End date",
            "type": "datetime",
            "required": False,
            "description": "The end date and time to use for item filtering. Must be RFC3339 compliant.",
        },
        "aoi": {
            "name": "aoi",
            "full_name": "Area of Interest",
            "type": "polygon",
            "required": True,
            "description": "The Area of Interest as GeoJSON (polygon).",
        },
    },
    "outputs": {
        "stac_collection": {
            "name": "stac_collection",
            "full_name": "STAC collection",
            "type": "stac_collection",
            "description": "The STAC collection with results.",
        },
    },
}
NDMI_FUNCTION_SPEC = {
    "identifier": "ndmi",
    "name": "NDMI: Normalised Difference Moisture Index",
    "description": "Calculates Normalised Difference Moisture Index.",
    "standalone": True,
    "cwl_href": "https://raw.githubusercontent.com/EO-DataHub/eodh-workflows/main/cwl_files/ndmi-app.cwl",
    "inputs": {
        "stac_collection": {
            "name": "stac_collection",
            "full_name": "STAC collection",
            "type": "string",
            "required": False,
            "default": "sentinel-2-l2a",
            "description": "The STAC collection to use.",
            "options": ["sentinel-2-l2a"],
        },
        "date_start": {
            "name": "date_start",
            "full_name": "Start date",
            "type": "datetime",
            "required": False,
            "description": "The start date and time to use for item filtering. Must be RFC3339 compliant.",
        },
        "date_end": {
            "name": "date_end",
            "full_name": "End date",
            "type": "datetime",
            "required": False,
            "description": "The end date and time to use for item filtering. Must be RFC3339 compliant.",
        },
        "aoi": {
            "name": "aoi",
            "full_name": "Area of Interest",
            "type": "polygon",
            "required": True,
            "description": "The Area of Interest as GeoJSON (polygon).",
        },
    },
    "outputs": {
        "stac_collection": {
            "name": "stac_collection",
            "full_name": "STAC collection",
            "type": "stac_collection",
            "description": "The STAC collection with results.",
        },
    },
}
FUNCTIONS = [
    NDVI_FUNCTION_SPEC,
    EVI_FUNCTION_SPEC,
    SAVI_FUNCTION_SPEC,
    NDMI_FUNCTION_SPEC,
    CLIP_FUNCTION_SPEC,
]
PRESETS_REGISTRY: dict[str, dict[str, Any]] = {f["identifier"]: f for f in FUNCTIONS}  # type: ignore[misc]
