### Search WF results
POST {{eodh_stac_api_url}}/catalogs/user-datasets/{{workspace}}/processing-results/cat_{{job_id}}/search
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json

{
    "collections": [
      "col_{{job_id}}"
    ],
    "fields": {
      "include": [],
      "exclude": []
    },
    "limit": 1,
    "sortby": [
      {
        "field": "properties.datetime",
        "direction": "desc"
      }
    ],
    "filter-lang": "cql-json"
}


### Get user catalogs
GET {{eodh_stac_api_url}}/catalogs/user-datasets/{{workspace}}/processing-results
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json


### Get catalog details
GET {{eodh_stac_api_url}}/catalogs/user-datasets/{{workspace}}/processing-results/cat_{{job_id}}
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json


### Get collections under catalog
GET {{eodh_stac_api_url}}/catalogs/user-datasets/{{workspace}}/processing-results/cat_{{job_id}}/collections
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json


### Get collection details
GET {{eodh_stac_api_url}}/catalogs/user-datasets/{{workspace}}/processing-results/cat_{{job_id}}/collections/col_{{job_id}}
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json


### Get items for a collection
GET {{eodh_stac_api_url}}/catalogs/user-datasets/{{workspace}}/processing-results/cat_{{job_id}}/collections/col_{{job_id}}/items
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json
