@api_version=v1.2

### Ping
GET {{api_url}}/{{api_version}}/health/ping
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Introspect Token
POST {{api_url}}/{{api_version}}/auth/token/introspection
Accept: application/json
Authorization: Bearer {{token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### List Functions
GET {{api_url}}/{{api_version}}/action-creator/functions
Accept: application/json
Authorization: Bearer {{token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### List Functions For Collection
GET {{api_url}}/{{api_version}}/action-creator/functions?dataset=sentinel-2-l2a
Accept: application/json
Authorization: Bearer {{token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
### List Functions For Non Existent Collection
GET {{api_url}}/{{api_version}}/action-creator/functions?collection=i-dont-exist
Accept: application/json
Authorization: Bearer {{token}}

> {%
    client.test("Request status is 404", function() {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}

### List Presets
GET {{api_url}}/{{api_version}}/action-creator/presets
Accept: application/json
Authorization: Bearer {{token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### List WF Submissions No Params
GET {{api_url}}/{{api_version}}/action-creator/workflow-submissions
Accept: application/json
Authorization: Bearer {{token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
