@api_version=v1.2

### Ping
GET {{api_url}}/{{api_version}}/health/ping
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Token
POST {{api_url}}/{{api_version}}/auth/token
Accept: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Introspect Token
POST {{api_url}}/{{api_version}}/auth/token/introspection
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### List Presets
GET {{api_url}}/{{api_version}}/action-creator/presets
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### List Functions
GET {{api_url}}/{{api_version}}/action-creator/functions
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### List Functions For Collection
GET {{api_url}}/{{api_version}}/action-creator/functions?collection=sentinel-2-l2a-ard
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### List Functions For Non Existent Collection
GET {{api_url}}/{{api_version}}/action-creator/functions?collection=i-dont-exist
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

> {%
    client.test("Request status is 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### List Function Submissions No Params
GET {{api_url}}/{{api_version}}/action-creator/submissions
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### List Function Submissions Pagination
GET {{api_url}}/{{api_version}}/action-creator/submissions?page=1&order_by=submitted_at&order_direction=desc&per_page=5&status=running
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Run LULC Change
POST {{api_url}}/{{api_version}}/action-creator/submissions
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

< v1_2_models/lulc-change.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 202, "Response status is not 202");
    });
%}

### Run NDVI
POST {{api_url}}/{{api_version}}/action-creator/submissions
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

< v1_2_models/ndvi.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 202, "Response status is not 202");
    });
%}

### Run NDVI + Clip
POST {{api_url}}/{{api_version}}/action-creator/submissions
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

< v1_2_models/ndvi-clip.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 202, "Response status is not 202");
    });
%}

### Run CYA + Clip
POST {{api_url}}/{{api_version}}/action-creator/submissions
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

< v1_2_models/cya-clip.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 202, "Response status is not 202");
    });
%}

### Run Water Quality
POST {{api_url}}/{{api_version}}/action-creator/submissions
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

< v1_2_models/water-quality.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 202, "Response status is not 202");
    });
%}

### Run Scatter NDVI
POST {{api_url}}/{{api_version}}/action-creator/submissions
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

< v1_2_models/scatter-ndvi.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 202, "Response status is not 202");
    });
%}

### Run Scatter Water Quality
POST {{api_url}}/{{api_version}}/action-creator/submissions
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

< v1_2_models/scatter-water-quality.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 202, "Response status is not 202");
    });
%}

### Run Scatter Land Cover Change - Corine
POST {{api_url}}/{{api_version}}/action-creator/submissions
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

< v1_2_models/scatter-lcc-corine.json

### Run Scatter Land Cover Change - Global LC
POST {{api_url}}/{{api_version}}/action-creator/submissions
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

< v1_2_models/scatter-lcc-global.json

### Get Job Status
GET {{api_url}}/{{api_version}}/action-creator/submissions/a78b7580-d8b7-11ef-ac87-7acca6d0ccd7
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Cancel Job
DELETE {{api_url}}/{{api_version}}/action-creator/submissions/bafd6490-d8b0-11ef-92bb-7acca6d0ccd7
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}

### Get data for WQ Chart - selected assets
POST {{api_url}}/{{api_version}}/catalogue/stac/catalogs/user-datasets/catalogs/{{username}}/catalogs/processing-results/catalogs/water-quality/catalogs/cat_01e116ec-bdf2-11ef-a2af-8ef03814f15e/charts
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

{
    "assets": ["cdom", "doc"],
    "stac_query": {
        "limit": 50,
        "sortby": [
            {
                "field": "properties.datetime",
                "direction": "asc"
            }
        ],
        "filter_lang": "cql-json",
        "filter": {
            "op": "between",
            "args": [
                {
                    "property": "properties.datetime"
                },
                "1992-07-01T00:00:00.000Z",
                "2025-07-02T23:59:59.999Z"
            ]
        },
        "fields": {}
    }
}

### Get data for WQ Chart - all assets - no scatter
POST {{api_url}}/{{api_version}}/catalogue/stac/catalogs/user-datasets/catalogs/{{username}}/catalogs/processing-results/catalogs/water-quality/catalogs/cat_01e116ec-bdf2-11ef-a2af-8ef03814f15e/charts
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

{
    "stac_query": {
        "limit": 50,
        "sortby": [
            {
                "field": "properties.datetime",
                "direction": "asc"
            }
        ],
        "filter_lang": "cql-json",
        "filter": {
            "op": "between",
            "args": [
                {
                    "property": "properties.datetime"
                },
                "1992-07-01T00:00:00.000Z",
                "2025-07-02T23:59:59.999Z"
            ]
        },
        "fields": {}
    }
}

### Get data for WQ Chart - all assets - scatter
POST {{api_url}}/{{api_version}}/catalogue/stac/catalogs/user-datasets/catalogs/{{username}}/catalogs/processing-results/catalogs/water-quality/catalogs/cat_244fb332-de68-11ef-94fd-12e2ea552ab2/charts
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

{
    "stac_query": {
        "limit": 50,
        "sortby": [
            {
                "field": "properties.datetime",
                "direction": "asc"
            }
        ],
        "filter_lang": "cql-json",
        "filter": {
            "op": "between",
            "args": [
                {
                    "property": "properties.datetime"
                },
                "1992-07-01T00:00:00.000Z",
                "2025-07-02T23:59:59.999Z"
            ]
        },
        "fields": {}
    }
}

### Get data for LC Chart - no scatter
POST {{api_url}}/{{api_version}}/catalogue/stac/catalogs/user-datasets/catalogs/{{username}}/catalogs/processing-results/catalogs/land-cover-change/catalogs/cat_3d13f7fa-eecd-11ef-bc57-ca3e8cd28499/charts
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

{
    "assets": ["data"],
    "stac_query": {
        "limit": 50,
        "sortby": [
            {
                "field": "properties.datetime",
                "direction": "asc"
            }
        ],
        "filter_lang": "cql-json",
        "filter": {
            "op": "between",
            "args": [
                {
                    "property": "properties.datetime"
                },
                "1992-07-01T00:00:00.000Z",
                "2025-07-02T23:59:59.999Z"
            ]
        },
        "fields": {}
    }
}

### Get data for LC Chart - scatter
POST {{api_url}}/{{api_version}}/catalogue/stac/catalogs/user-datasets/catalogs/{{username}}/catalogs/processing-results/catalogs/land-cover-change/catalogs/cat_e454dbce-de4c-11ef-a182-12e2ea552ab2/charts
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

{
    "assets": ["data"],
    "stac_query": {
        "limit": 50,
        "sortby": [
            {
                "field": "properties.datetime",
                "direction": "asc"
            }
        ],
        "filter_lang": "cql-json",
        "filter": {
            "op": "between",
            "args": [
                {
                    "property": "properties.datetime"
                },
                "1992-07-01T00:00:00.000Z",
                "2025-07-02T23:59:59.999Z"
            ]
        },
        "fields": {}
    }
}

### Get data for LC Chart - 1990 missing data
POST {{api_url}}/{{api_version}}/catalogue/stac/catalogs/user-datasets/catalogs/{{username}}/catalogs/processing-results/catalogs/land-cover-change/catalogs/cat_8de9589e-e222-11ef-84a9-86a1f8f9b25e/charts
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

{
  "stac_query": {
    "limit": 50,
    "sortby": [
      {
        "field": "properties.datetime",
        "direction": "desc"
      }
    ],
    "filter-lang": "cql-json",
    "filter": {
      "op": "and",
      "args": [
        {
          "op": "=",
          "args": [
            {
              "property": "collection"
            },
            "col_8de9589e-e222-11ef-84a9-86a1f8f9b25e"
          ]
        },
        {
          "op": "between",
          "args": [
            {
              "property": "properties.datetime"
            },
            "1990-01-01T00:00:00.000Z",
            "2018-01-01T23:59:59.999Z"
          ]
        }
      ]
    },
    "fields": {}
  }
}

### Batch delete
DELETE {{api_url}}/{{api_version}}/action-creator/submissions
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

{
  "remove_statuses": [
    "failed"
  ],
  "remove_all_before": "2025-02-15T13:18:40.108Z",
  "remove_all_after": null,
  "remove_jobs_without_results": false,
  "max_jobs_to_process": 1000
}
