name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  pr-checks:
    defaults:
      run:
        # Ensure the environment is activated
        # <https://github.com/mamba-org/provision-with-micromamba#important>
        shell: bash -l {0}

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: ci-env
        environment-file: conda-lock-tmp.yml
        init-shell: >-
          bash

    - name: Install pre-commit
      run: |
        pre-commit install

    - name: Run simplified pre-commit hooks
      run: |
        SKIP=pytest-check pre-commit run --all-files

    - name: Run unit tests
      run: |
        pytest --cov=src tests/ --cov-report xml:coverage/coverage.xml
      env:
        EODH_AUTH__BASE_URL: ${{ secrets.EODH_AUTH__BASE_URL }}
        EODH_AUTH__REALM: ${{ secrets.EODH_AUTH__REALM }}
        EODH_AUTH__USERNAME: ${{ secrets.EODH_AUTH__USERNAME }}
        EODH_AUTH__PASSWORD: ${{ secrets.EODH_AUTH__PASSWORD }}
        EODH_AUTH__CLIENT_ID: ${{ secrets.EODH_AUTH__CLIENT_ID }}
        EODH_AUTH__CLIENT_SECRET: ${{ secrets.EODH_AUTH__CLIENT_SECRET }}

    - name: Get code coverage
      uses: orgoro/coverage@v3.2
      with:
          coverageFile: coverage/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.7
          thresholdNew: 0.7
          thresholdModified: 0.0
