name: PR

on:
  push:
    branches:
      - cicd
jobs:
#  pre-commit-checks:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Check out the repository
#        uses: actions/checkout@v2
#
#      - name: Set up Python 3.11
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.11'
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install pre-commit
#          pre-commit install
#
#      - name: Run simplified pre-commit hooks
#        run: |
#          SKIP=pytest-check pre-commit run --all-files
#
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}
          IMAGE_TAG: "latest"

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
      - name: Build Docker image
        run: |
          # Build the Docker image
          docker build -t ${{ secrets.ECR_REPOSITORY }}$IMAGE_TAG .

          # Tag the image
          ECR_URI=$(aws ecr describe-repositories --repository-names ${{ secrets.ECR_REPOSITORY }} --region ${{ vars.AWS_REGION }} --query "repositories[0].repositoryUri" --output text)
          docker tag ${{ secrets.ECR_REPOSITORY }}$IMAGE_TAG $ECR_URI:$IMAGE_TAG
