name: PR

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - name: Setup cwltool
        run: |
          sudo apt update
          sudo apt install -y cwltool

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          pip install pre-commit==3.8.0 pytest pytest-asyncio pytest-cov pytest-mock pytest-pretty flaky
          pre-commit install

      - name: Run simplified pre-commit hooks
        run: |
          SKIP=pytest-check pre-commit run --all-files

      - name: Run unit tests
        run: |
          pytest -vv --cov=src tests/ --cov-report xml:coverage/coverage.xml
        env:
          EODH_AUTH__BASE_URL: ${{ secrets.EODH_AUTH__BASE_URL }}
          EODH_AUTH__REALM: ${{ secrets.EODH_AUTH__REALM }}
          EODH_AUTH__USERNAME: ${{ secrets.EODH_AUTH__USERNAME }}
          EODH_AUTH__PASSWORD: ${{ secrets.EODH_AUTH__PASSWORD }}
          EODH_AUTH__CLIENT_ID: ${{ secrets.EODH_AUTH__CLIENT_ID }}
          EODH_AUTH__API_TOKEN: ${{ secrets.EODH_AUTH__API_TOKEN }}
          EODH_AUTH__WORKSPACE_TOKENS_URL: ${{ secrets.EODH_AUTH__WORKSPACE_TOKENS_URL }}
          EODH_AUTH__TMP_S3_CREDENTIALS_URL: ${{ secrets.EODH_AUTH__TMP_S3_CREDENTIALS_URL }}
          ADES__URL: ${{ secrets.ADES__URL }}
          ADES__OGC_PROCESSES_API_PATH: ${{ secrets.ADES__OGC_PROCESSES_API_PATH }}
          ADES__OGC_JOBS_API_PATH: ${{ secrets.ADES__OGC_JOBS_API_PATH }}
          SENTINEL_HUB__CLIENT_ID: ${{ secrets.SENTINEL_HUB__CLIENT_ID }}
          SENTINEL_HUB__CLIENT_SECRET: ${{ secrets.SENTINEL_HUB__CLIENT_SECRET }}
          SENTINEL_HUB__TOKEN_URL: ${{ secrets.SENTINEL_HUB__TOKEN_URL }}
          SENTINEL_HUB_STAC_API__ENDPOINT: ${{ secrets.SENTINEL_HUB_STAC_API__ENDPOINT }}
          EODH_STAC_API__ENDPOINT: ${{ secrets.EODH_STAC_API__ENDPOINT }}

      - name: Get code coverage
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.0
          thresholdNew: 0.0
          thresholdModified: 0.0
