name: PR

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version-file: "pyproject.toml"

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@b1de5da23ed0a6d14e0aeee8ed52fdd87af2363c # v2.0.2

      - name: Setup cwltool
        run: |
          sudo apt update
          sudo apt install -y cwltool

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run simplified pre-commit hooks
        run: |
          SKIP=pytest-check uv run pre-commit run --all-files

      - name: Run unit tests
        run: |
          uv run pytest -vv --cov=src tests/ --cov-report xml:coverage/coverage.xml
        env:
          EODH__BASE_URL: ${{ vars.EODH__BASE_URL }}
          EODH__REALM: ${{ vars.EODH__REALM }}
          EODH__USERNAME: ${{ secrets.EODH__USERNAME }}
          EODH__PASSWORD: '${{ secrets.EODH__PASSWORD }}'
          EODH__CLIENT_ID: ${{ secrets.EODH__CLIENT_ID }}
          EODH__WORKSPACE_SERVICES_ENDPOINT: ${{ vars.EODH__WORKSPACE_SERVICES_ENDPOINT }}
          EODH__STAC_API_ENDPOINT: ${{ vars.EODH__STAC_API_ENDPOINT }}
          EODH__CEDA_STAC_CATALOG_PATH: ${{ vars.EODH__CEDA_STAC_CATALOG_PATH }}
          ADES__URL: ${{ vars.ADES__URL }}
          ADES__OGC_PROCESSES_API_PATH: ${{ vars.ADES__OGC_PROCESSES_API_PATH }}
          ADES__OGC_JOBS_API_PATH: ${{ vars.ADES__OGC_JOBS_API_PATH }}
          SENTINEL_HUB__CLIENT_ID: ${{ secrets.SENTINEL_HUB__CLIENT_ID }}
          SENTINEL_HUB__CLIENT_SECRET: ${{ secrets.SENTINEL_HUB__CLIENT_SECRET }}
          SENTINEL_HUB__TOKEN_URL: ${{ vars.SENTINEL_HUB__TOKEN_URL }}
          SENTINEL_HUB__STAC_API_ENDPOINT: ${{ vars.SENTINEL_HUB__STAC_API_ENDPOINT }}

      - name: Get code coverage
        uses: orgoro/coverage@3f13a558c5af7376496aa4848bf0224aead366ac # v3.2
        with:
          coverageFile: coverage/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.0
          thresholdNew: 0.0
          thresholdModified: 0.0
